[package]
name = "dhcp-arp"
version = "0.1.0"
authors = ["hedgar"]

[dependencies]
eui48 = "0.4.1"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.43"
nix = "0.13.0"

[target.'cfg(target_os = "windows")'.dependencies]
tokio = { version = "1.4", features = ["process"] }
